version: '3.8'

services:
  mascot-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mascot-agent
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ELIZA_UI_ENABLE=true
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount data directory for any local file storage
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:3000/health || curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mascot-network

networks:
  mascot-network:
    driver: bridge

volumes:
  logs:
    driver: local
  data:
    driver: local