version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: mascot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mascot-agent
    networks:
      - mascot-network

  mascot-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mascot-agent
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ELIZA_UI_ENABLE=true
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:3000/health || curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mascot-network

networks:
  mascot-network:
    driver: bridge

volumes:
  logs:
    driver: local
  data:
    driver: local